name: DwarfCraft
description: A skills and progression plugin for character development in RPG worlds.
author: smartaleq
main: com.smartaleq.bukkit.dwarfcraft.DwarfCraft
version: 1.0
commands:
   dc:
      description: DwarfCraft commands
      usage: